### PR TITLE
Make bar chart clickable

### PR DESCRIPTION
**Pull request by rsvoboda**
Make bar chart clickable

Commented out `console.table(...)` lines are left in the code intentionally.

### CODE REVIEW

**Comment by gsmet** [comment]
Is it normal that even if I click on the green part, I end up with open issues? I agree it's the most interesting part but I was a bit surprised.

Also, wondering if we could have a `pointer` cursor.

**Comment by rsvoboda** [comment]
Man, you are so demanding. Working on it.

**Comment by rsvoboda** [comment]
@gsmet ready for second round of review

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks!

**Pull request merged**
