### PR TITLE
Deep dive reports for bugs and enhancements

### PR DESCRIPTION
**Pull request by rsvoboda**
Deep dive reports for bugs and enhancements

Reports available under `/bugs` and `/enhancements` endpoints

Example for bugs:
Screenshot 2020-10-15 at 10 35 06

### CODE REVIEW

**Comment by rsvoboda** [comment]
```graphql
{
  created:search(query: "repo:quarkusio/quarkus label:kind/bug is:issue created:2020-09-01..2020-09-30", type: ISSUE, first: 1) {
    issueCount
  }
  createdAndStilOpen:search(query: "repo:quarkusio/quarkus label:kind/bug is:issue is:open created:2020-09-01..2020-09-30", type: ISSUE, first: 1) {
    issueCount
  }
  createdAndClosedNow:search(query: "repo:quarkusio/quarkus label:kind/bug is:issue is:closed created:2020-09-01..2020-09-30", type: ISSUE, first: 1) {
    issueCount
  }
  closed:search(query: "repo:quarkusio/quarkus label:kind/bug is:issue is:closed closed:2020-09-01..2020-09-30", type: ISSUE, first: 1) {
    issueCount
  }
  createdAndClosed:search(query: "repo:quarkusio/quarkus label:kind/bug is:issue is:closed created:2020-09-01..2020-09-30 closed:2020-09-01..2020-09-30", type: ISSUE, first: 1) {
    issueCount
  }
  rateLimit {
    limit
    cost
    remaining
    resetAt
  }
}
```

returns `"cost": 1,`. 

https://docs.github.com/en/free-pro-team@latest/graphql/overview/resource-limitations#rate-limit says `The GraphQL API v4 rate limit is 5,000 points per hour.` So we don't need to be concerned about hitting this limit. 

cost: update twice a hour, 22 months, asking for bugs and enhancements => 2 * 22 * 2 = 88
In 3 years time-frame the cost will be 2 * 36 * 2 = 144

**Comment by gsmet** [comment]
Interesting!

A couple of small details:
- could the closed issues be green in the first graph?
- I would have the legend say "Issues created per month" / Closed | Still open
- I don't understand right away what the second graph is about?
. Maybe `Activity per month`
. Opened during month | Closed during month | Both opened and closed during month
. Opened should be red, Closed should be green, the last one can stay blue (but I think I would use the darker one)

**Comment by rsvoboda** [comment]
UI design is the biggest pain 🤣

**Comment by rsvoboda** [comment]
@gsmet PR updated, here is screenshot of current version:
Screenshot 2020-10-15 at 17 28 14

**Comment by gsmet** [comment]
OK, let's get this in, we can adjust the nav later if need be.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks!

**Comment by rsvoboda** [comment]
Thanks for merging, any ETA when it will be deployed?

**Comment by gsmet** [comment]
It's deployed.

**Pull request merged**
